#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy

sudo sh -c 'echo "ENABLED=1" >> /etc/default/haproxy'
sudo mv /etc/haproxy/haproxy.cfg{,.original}
sudo touch /etc/haproxy/haproxy.cfg
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

# Default settings
defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

# Frontend configuration
frontend app
    bind *:80
    default_backend web_server

# Backend configuration
backend web_server
    balance roundrobin
    server 339955-web-01 54.226.23.44:80
    server 339955-web-02 54.242.170.193:80  
EOF

sudo service haproxy restart
