#!/usr/bin/env bash
# Configuration that blocks all incoming traffic, except the following TCP ports:
# 22(SSH), 443(HTTPS SSl), 80(HTTP)

sudo apt-get update
sudo apt-get install -y ufw
sudo ufw enable 
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw default deny incoming
sudo ufw status numbered
